packages:
  - "modules/*/*"

catalog:
  "@types/node": ^22
  "@vector-im/compound-design-tokens": ^10.2.2
  "@vector-im/compound-web": ^9.4.1
  typescript: ^5.7.2
  vite: ^7.0.0

allowBuilds:
  "@matrix-org/matrix-sdk-crypto-nodejs": true
  '@parcel/watcher': false
  cpu-features: true
  esbuild: true
  protobufjs: true
  ssh2: true
