import type { OpenProjectWorkPackage } from "../../src/openproject/Types";

export const BASE_URL = new URL("https://openproject.example/");

export const WORK_PACKAGE: OpenProjectWorkPackage = {
  _type: "WorkPackage",
  id: 50,
  lockVersion: 0,
  subject: "Build the bridge",
  description: {
    format: "markdown",
    raw: "A short description",
    html: "<p>A short description</p>",
  },
  scheduleManually: true,
  startDate: null,
  dueDate: null,
  derivedStartDate: null,
  derivedDueDate: null,
  estimatedTime: null,
  derivedEstimatedTime: null,
  derivedRemainingTime: null,
  duration: null,
  ignoreNonWorkingDays: false,
  percentageDone: null,
  derivedPercentageDone: null,
  createdAt: "2025-05-08T13:19:12.275Z",
  updatedAt: "2025-05-08T13:19:12.309Z",
  _embedded: {
    type: {
      id: 2,
      name: "Milestone",
      isDefault: true,
      createdAt: "2025-05-08T11:36:17.444Z",
      updatedAt: "2025-05-08T11:36:17.444Z",
      color: "#35C53F",
      _links: { self: { href: "/api/v3/types/2", title: "Milestone" } },
    },
    priority: {
      id: 8,
      name: "Normal",
      isDefault: true,
      isActive: true,
      createdAt: "2025-05-08T11:36:17.444Z",
      updatedAt: "2025-05-08T11:36:17.444Z",
      color: "#74C0FC",
      _links: { self: { href: "/api/v3/priorities/8" } },
    },
    project: {
      id: 1,
      identifier: "demo-project",
      name: "Demo project",
      active: true,
      public: true,
      createdAt: "2025-05-08T11:36:19.527Z",
      updatedAt: "2025-05-08T11:36:19.527Z",
      description: {
        format: "markdown",
        raw: "Project description",
        html: "<p>Project description</p>",
      },
      _links: { memberships: { href: "/api/v3/memberships" } },
    },
    status: {
      id: 1,
      name: "New",
      isClosed: false,
      isDefault: true,
      isReadonly: false,
      color: "#D9D9D9",
      _links: { self: { href: "/api/v3/statuses/1", title: "New" } },
    },
    author: {
      id: 10,
      name: "OpenProject Admin",
      login: "admin",
      createdAt: "2025-05-08T11:36:17.444Z",
      updatedAt: "2025-05-08T11:36:17.444Z",
      avatar: "/avatars/10",
      status: "active",
      _links: {
        self: { href: "/api/v3/users/10", title: "OpenProject Admin" },
      },
    },
    assignee: {
      id: 11,
      name: "Alice",
      login: "alice",
      createdAt: "2025-05-08T11:36:17.444Z",
      updatedAt: "2025-05-08T11:36:17.444Z",
      avatar: "/avatars/11",
      status: "active",
      _links: { self: { href: "/api/v3/users/11", title: "Alice" } },
    },
  },
  _links: { self: {} },
};
