{{- if not .Values.hookshot.existingSecret.passkey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "hookshot.passkeySecretName" . }}
  namespace: {{ template "hookshot.namespace" . }}
  labels:
    {{- include "hookshot.labels" . | nindent 4 }}
{{- with .Values.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
data:
  passkey.pem: |-
    {{ toYaml .Values.hookshot.passkey | nindent 4 }}
{{- end }}
