{{- if not .Values.hookshot.existingSecret.registration }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "hookshot.registrationSecretName" . }}
  namespace: {{ template "hookshot.namespace" . }}
  labels:
    {{- include "hookshot.labels" . | nindent 4 }}
{{- with .Values.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
data:
  registration.yaml: |-
    {{- toYaml .Values.hookshot.registration | nindent 4 }}
{{- end }}
