/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class ExternalObject<T> {
  readonly '': {
    readonly '': unique symbol
    [K: symbol]: T
  }
}
export interface IssueLabelDetail {
  color?: string | undefined | null
  name: string
  description?: string | undefined | null
}
export interface MatrixMessageFormatResult {
  html: string
  plain: string
}
export function formatLabels(array: Array<IssueLabelDetail>): MatrixMessageFormatResult
/** Generate a URL for a given Jira Issue object. */
export function getPartialBodyForJiraIssue(jiraIssue: JiraIssue): JiraIssueMessageBody
/** Generate a URL for a given Jira Issue object. */
export function hashId(id: string): string
export interface JiraProject {
  self: string
  id: string
  key: string
}
export interface JiraIssue {
  self: string
  id: string
  key: string
  fields: JiraIssueFields
}
export interface JiraIssueFields {
  project: JiraProject
}
export interface JiraIssueLight {
  self: string
  key: string
}
export interface JiraIssueSimpleItem {
  id: string
  key: string
  api_url: string
}
export interface JiraIssueMessageBody {
  uk.half-shot.matrix-hookshot.jira.issue: JiraIssueSimpleItem
  uk.half-shot.matrix-hookshot.jira.project: JiraIssueSimpleItem
  external_url: string
}
/** Generate a URL for a given Jira Issue object. */
export function generateJiraWeblinkFromIssue(jiraIssue: JiraIssueLight): string
