id: matrix-hookshot # This can be anything, but must be unique within your homeserver
as_token: ze0phie8yaefoo0eep9tha9baeKee2Da # This again can be a random string
hs_token: ao5oogiesah9NoHoh2ohgaiteitualai # ..as can this
namespaces:
  rooms: []
  users: # In the following, foobar is your homeserver's domain
    - regex: "@_github_.*:foobar"
      exclusive: true
    - regex: "@_gitlab_.*:foobar"
      exclusive: true
    - regex: "@_jira_.*:foobar"
      exclusive: true
    - regex: "@_webhooks_.*:foobar" # Where _webhooks_ is set by userIdPrefix in config.yml
      exclusive: true
    - regex: "@feeds:foobar" # Matches the localpart of all serviceBots in config.yml
      exclusive: true
  aliases:
    - regex: "#github_.+:foobar" # Where foobar is your homeserver's domain
      exclusive: true

sender_localpart: hookshot
url: "http://app:9993" # This should match the bridge.port in your config file
rate_limited: false

# If enabling encryption
de.sorunome.msc2409.push_ephemeral: true
push_ephemeral: true
org.matrix.msc3202: true
