name: Devenv

on:
  push:
    branches: [main]
    paths:
      - "/devenv*"
  pull_request:
    branches: [main]
    paths:
      - "/devenv*"

permissions: {}

jobs:
  test-nix-env:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          persist-credentials: false
      - uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31
      - uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv
      - name: Build the devenv shell and run any git hooks
        run: devenv test
