name: Build docs

on:
  push:
    branches: [main]
    paths-ignore:
      - changelog.d/**'
  pull_request:
    branches: [main]
    paths-ignore:
      - changelog.d/**'
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4.3.0
      - name: Use Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: .node-version
          cache: 'pnpm'

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6.0.0

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@ee69d230fe19748b7abf22df32acaa93833fad08 # v2.0.0
        with:
          mdbook-version: "0.4.11"

      # We want to install matrix-appservice-bridge, which we depend on.
      - run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Get release tag
        if: github.event_name == 'release'
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set version of docs
        if: github.event_name == 'release'
        run: echo 'window.HOOKSHOT_VERSION = "${RELEASE_VERSION}";' > ./docs/_site/version.js

      - run: mdbook build

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: "gh-pages"
          path: "./gh-pages"
          persist-credentials: false

      - name: Move release
        if: github.event_name == 'release'
        run: mv book "./gh-pages/${RELEASE_VERSION}"

      - name: Update latest
        if: github.event_name != 'release'
        run: rm -R ./gh-pages/latest && mv ./book ./gh-pages/latest

      - name: Upload artifact
        id: deployment
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: "./gh-pages"

  # Deployment job
  deploy:
    # Only push if this is main, otherwise we just want to build
    if: github.event_name == 'release' || github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
