name: Newsfile

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, labeled]

permissions: {}

jobs:
  changelog:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    # No newsfile required for tasks
    if: ${{ !contains( github.event.pull_request.labels.*.name, 'T-Task') }}
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with: # Needed for comparison
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6
        with:
          python-version: "3.14"
      - run: pip install towncrier~=25.8.0
      - name: ":newspaper: Newsfile"
        run: python3 -m towncrier.check --compare-with=origin/main
