on:
  push:
    tags: ["[0-9].[0-9].[0-9]"]

permissions: {}

jobs:
  draft-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          persist-credentials: false
      - name: Create release
        env:
          REF_NAME: ${{ github.ref_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
        run: |
          git fetch --tags --force
          RELEASE_NAME="${REF_NAME} $(date +'%Y-%m-%d')"
          git tag -l --format='%(contents:body)' "${REF_NAME}" > next-changelog.txt
          gh release create "${REF_NAME}" \
              --repo="$GITHUB_REPOSITORY" \
              --title="$RELEASE_NAME" \
              --notes-file="next-changelog.txt" \
              --draft
