name: Build Storybook

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions: {}

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9f698171ed81b15d1823a05fc7211befd50c8ae0 # v6.0.3
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@008330803749db0355799c700092d9a85fd074e9 # v6.0.9
      - name: Use Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: .node-version
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm lint:storybook
      - run: pnpm --filter openproject-module lint:types
      - run: pnpm --filter openproject-module prepare
      - run: pnpm build:storybook
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: storybook
          path: storybook-static
